### PR TITLE
Added GetFieldValue test to retrieve Stream

### LINKED ISSUE #144: Add tests for GetFieldValue checking possibility of getting a stream or text reader
Originally posted by @roji in https://github.com/npgsql/npgsql/issues/2446#issue-434779986:

> [As mentioned by @Wraith2](https://github.com/dotnet/corefx/issues/35012#issuecomment-484462213), in SqlClient `DbDataReader.GetFieldValue<T>()` can be used to get a Stream or TextReader, exactly in the same way as currently returned by the dedicated `GetStream()` and `GetTextReader()` methods. We should implement this as well.
> 
> This has the advantage of also providing async column access via `GetFieldValueAsync()` without adding new `GetStreamAsync()` and `GetTextReaderAsync()`.

@bgrainger, assign this to me, please. I will take a care of it.

### PR DESCRIPTION
**Pull request by YohDeadfall**
Fixes #144

### CODE REVIEW

**Review by roji — APPROVED** [review]
Shouldn't these be in the upstream tests? Or is the plan to remove these once they're implemented there?

**Comment by YohDeadfall** [comment]
What do you mean? As I understand the base class made to share tests across provides and all of them should support the behavior.

**Comment by YohDeadfall** [comment]
As I understood Wraith2, this is supported by SqlClient and by Npgsql now. Moreover, getting `TextReader` is a standard thing, so why not for `Stream`?

**Comment by roji** [comment]
> What do you mean? As I understand the base class made to share tests across provides and all of them should support the behavior.

I do agree this is a good to have as a standard provider behavior - I'm just not sure this has been properly discussed etc.

> As I understood Wraith2, this is supported by SqlClient and by Npgsql now. Moreover, getting TextReader is a standard thing, so why not for Stream?

I tried running the following code with 2.1.0-preview1.20235.1:
 
```c#
using var conn = new SqlConnection("...");
conn.Open();
using var cmd = new SqlCommand("SELECT @p", conn);
cmd.Parameters.AddWithValue("p", new byte[] { 1, 2, 3 });
using var reader = cmd.ExecuteReader();
reader.Read();
_ = reader.GetFieldValue<Stream>(0);
```

This gives me the following exception message:

```
Unable to cast object of type 'System.Byte[]' to type 'System.IO.Stream'.
```

Maybe @Wraith2 can provide some info...

**Comment by Wraith2** [comment]
I think the expectation in SqlClient is that if you want a stream you should call `GetStream`, no need for generics. There is logic in `GetFieldValue` which checks for `XmlReader` which means that you don't have to call `GetXmlReader` so there's a good argument that behaviour should be consistant for these types. I can't see any reason that we couldn't add in Stream as a valid generic parameter type for `GetFieldValue(Async)` we just haven't had reason to do so yet.

**Comment by roji** [comment]
@Wraith2 IIRC we discussed this together at some point, and the reason for allowing Stream and TextReader as generic arguments to GetFieldValue was that there aren't async methods for these (i.e. GetStreamAsync, GetTextReaderAsync). Rather than adding these new APIs, it was suggested to simply allow them to be passed to GetFieldValueAsync (and therefore also to GetFieldValue for consistency). I think it was even you who proposed this :smile:

**Comment by Wraith2** [comment]
I remember that. The work just hasn't been done for Stream, I was probaby distracted. Throw an issue into the sqlclient repo and to track i'll pick it up when I can.

**Comment by roji** [comment]
Thanks @Wraith2, no worries obviously. I've opened #732 to track, the original discussion between us on this starts in https://github.com/dotnet/runtime/issues/28596#issuecomment-484462213.

**Comment by bgrainger** [comment]
Thanks @YohDeadfall!

I made a small change in https://github.com/mysql-net/AdoNetApiTest/commit/2efb473b7370df0eab2ad0d535ef81495cf42f11 to test for the database provider's standard exception type; this allows SqlClient to keep throwing `SqlNullValueException` (instead of `InvalidCastException`) for these methods.

**Comment by bricelam** [comment]
I think I started this weirdness. While doing some initial investigation of dotnet/efcore#19991, I noticed that not everything was possible via `GetFieldValue<T>` which would require unnecessary special handling of these types.

**Comment by bricelam** [comment]
I think I filed dotnet/runtime#26756 with the idea of allowing users to write a value converter that goes from XmlReader to XmlDocument/XDocument, but I don't think I ever followed up on that after it was fixed...

**Pull request merged**
